name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        c-compiler: [ cl, clang, gcc ]
        include:
          - build-type: Release
          - os: windows-latest
            c-compiler: gcc
            generator: Ninja
          - os: windows-latest
            c-compiler: clang
            generator: Ninja
        exclude:
          - os: macos-latest
            c-compiler: cl
          - os: macos-latest
            c-compiler: gcc
          - os: ubuntu-latest
            c-compiler: cl

    steps:
      - uses: actions/checkout@v5

      - name: Install Ninja
        uses: lukka/get-cmake@latest

      - name: Setup MinGW
        if: matrix.os == 'windows-latest' && matrix.c-compiler == 'gcc'
        run: |
          echo "C:\ProgramData\Chocolatey\bin" >> $GITHUB_PATH
          echo "C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        shell: bash

      - name: Setup Clang
        if: matrix.os == 'windows-latest' && matrix.c-compiler == 'clang'
        run: echo "C:\Program Files\LLVM\bin" >> $GITHUB_PATH
        shell: bash

      - name: Configure
        shell: bash
        run: >
          cmake -B build
          ${{ matrix.generator && format('-G "{0}"', matrix.generator) || '' }}
          -DCMAKE_C_COMPILER=${{ matrix.c-compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build-type }} --parallel

      - name: Test
        run: ctest --test-dir build --build-config ${{ matrix.build-type }}
